INSERT INTO rol (nombre) values ("ADMINISTRADOR");
INSERT INTO rol (nombre) values ("SECRETARIO");
INSERT INTO rol (nombre) values ("VETERINARIO");

INSERT INTO permiso values ("READ_BUYER");
INSERT INTO permiso values ("CREATE_BUYER");
INSERT INTO permiso values ("UPDATE_BUYER");
INSERT INTO permiso (nombre) values ("DELETE_BUYER");
INSERT INTO permiso (nombre) values ("SEARCH_BUYER");
INSERT INTO permiso (nombre) values ("READ_PET");
INSERT INTO permiso (nombre)values ("CREATE_PET");
INSERT INTO permiso (nombre) values ("UPDATE_PET");
INSERT INTO permiso (nombre) values ("DELETE_PET");
INSERT INTO permiso (nombre) values ("READ_MEDICINE");
INSERT INTO permiso (nombre) values ("CREATE_MEDICINE");
INSERT INTO permiso (nombre) values ("UPDATE_MEDICINE");
INSERT INTO permiso (nombre) values ("DELETE_MEDICINE");
INSERT INTO permiso (nombre) values ("SEARCH_MEDICINE");
-- Auth
INSERT INTO permiso values ("READ_USER");
INSERT INTO permiso values ("CREATE_USER");
INSERT INTO permiso values ("UPDATE_USER");
INSERT INTO permiso (nombre) values ("DELETE_USER");
INSERT INTO permiso values ("READ_ROL");
INSERT INTO permiso values ("CREATE_ROL");
INSERT INTO permiso values ("UPDATE_ROL");
INSERT INTO permiso (nombre) values ("DELETE_ROL");
INSERT INTO permiso values ("READ_PERMISSION");
INSERT INTO permiso values ("CREATE_PERMISSION");
INSERT INTO permiso values ("UPDATE_PERMISSION");
INSERT INTO permiso (nombre) values ("DELETE_PERMISSION");
INSERT INTO permiso values ("READ_PERMISSIONXROL");
INSERT INTO permiso values ("CREATE_PERMISSIONXROL");
INSERT INTO permiso values ("UPDATE_PERMISSIONXROL");
INSERT INTO permiso (nombre) values ("DELETE_PERMISSIONXROL");

INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "READ_BUYER"), (select id from rol where nombre = "ADMINISTRADOR"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "CREATE_BUYER"), (select id from rol where nombre = "ADMINISTRADOR"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "UPDATE_BUYER"), (select id from rol where nombre = "ADMINISTRADOR"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "DELETE_BUYER"), (select id from rol where nombre = "ADMINISTRADOR"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "SEARCH_BUYER"), (select id from rol where nombre = "ADMINISTRADOR"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "READ_PET"), (select id from rol where nombre = "ADMINISTRADOR"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "CREATE_PET"), (select id from rol where nombre = "ADMINISTRADOR"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "UPDATE_PET"), (select id from rol where nombre = "ADMINISTRADOR"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "DELETE_PET"), (select id from rol where nombre = "ADMINISTRADOR"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "READ_MEDICINE"), (select id from rol where nombre = "ADMINISTRADOR"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "CREATE_MEDICINE"), (select id from rol where nombre = "ADMINISTRADOR"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "UPDATE_MEDICINE"), (select id from rol where nombre = "ADMINISTRADOR"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "DELETE_MEDICINE"), (select id from rol where nombre = "ADMINISTRADOR"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "SEARCH_MEDICINE"), (select id from rol where nombre = "ADMINISTRADOR"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "READ_USER"), (select id from rol where nombre = "ADMINISTRADOR"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "CREATE_USER"), (select id from rol where nombre = "ADMINISTRADOR"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "UPDATE_USER"), (select id from rol where nombre = "ADMINISTRADOR"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "DELETE_USER"), (select id from rol where nombre = "ADMINISTRADOR"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "READ_ROL"), (select id from rol where nombre = "ADMINISTRADOR"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "CREATE_ROL"), (select id from rol where nombre = "ADMINISTRADOR"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "UPDATE_ROL"), (select id from rol where nombre = "ADMINISTRADOR"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "DELETE_ROL"), (select id from rol where nombre = "ADMINISTRADOR"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "READ_PERMISSION"), (select id from rol where nombre = "ADMINISTRADOR"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "CREATE_PERMISSION"), (select id from rol where nombre = "ADMINISTRADOR"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "UPDATE_PERMISSION"), (select id from rol where nombre = "ADMINISTRADOR"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "DELETE_PERMISSION"), (select id from rol where nombre = "ADMINISTRADOR"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "READ_PERMISSIONXROL"), (select id from rol where nombre = "ADMINISTRADOR"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "CREATE_PERMISSIONXROL"), (select id from rol where nombre = "ADMINISTRADOR"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "UPDATE_PERMISSIONXROL"), (select id from rol where nombre = "ADMINISTRADOR"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "DELETE_PERMISSIONXROL"), (select id from rol where nombre = "ADMINISTRADOR"));

INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "READ_BUYER"), (select id from rol where nombre = "VETERINARIO"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "READ_PET"), (select id from rol where nombre = "VETERINARIO"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "CREATE_PET"), (select id from rol where nombre = "VETERINARIO"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "UPDATE_PET"), (select id from rol where nombre = "VETERINARIO"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "DELETE_PET"), (select id from rol where nombre = "VETERINARIO"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "READ_MEDICINE"), (select id from rol where nombre = "VETERINARIO"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "UPDATE_MEDICINE"), (select id from rol where nombre = "VETERINARIO"));

INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "READ_BUYER"), (select id from rol where nombre = "SECRETARIO"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "CREATE_BUYER"), (select id from rol where nombre = "SECRETARIO"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "UPDATE_BUYER"), (select id from rol where nombre = "SECRETARIO"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "DELETE_BUYER"), (select id from rol where nombre = "SECRETARIO"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "SEARCH_BUYER"), (select id from rol where nombre = "SECRETARIO"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "READ_PET"), (select id from rol where nombre = "SECRETARIO"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "CREATE_PET"), (select id from rol where nombre = "SECRETARIO"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "UPDATE_PET"), (select id from rol where nombre = "SECRETARIO"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "DELETE_PET"), (select id from rol where nombre = "SECRETARIO"));
INSERT INTO permiso_x_rol VALUES ((select id from permiso where nombre = "READ_MEDICINE"), (select id from rol where nombre = "SECRETARIO"));